/** Motivational scripture for the Home quote bubble. ref shown low-key under the text. */
export type Quote = { ref: string; text: string };

export const QUOTES: Quote[] = [
  { ref: "Philippians 4:13", text: "I can do all things through Christ who strengthens me." },
  { ref: "Galatians 6:9", text: "Let us not grow weary in doing good, for in due time we will reap our harvest if we do not give up." },
  { ref: "2 Timothy 4:7", text: "I have fought the good fight, I have finished the race, I have kept the faith." },
  { ref: "1 Corinthians 9:24", text: "Run the race in such a way as to win the prize." },
  { ref: "Hebrews 12:1", text: "Let us run with perseverance the race that lies before us." },
  { ref: "James 1:12", text: "Blessed is the one who perseveres in trial, for he will receive the crown of life." },
  { ref: "Romans 5:3-4", text: "Affliction produces endurance, endurance produces character, and character produces hope." },
  { ref: "Isaiah 40:31", text: "Those who hope in the Lord will renew their strength; they will soar on eagles' wings, run and not grow weary, walk and not faint." },
  { ref: "2 Corinthians 4:8-9", text: "We are afflicted in every way, but not crushed; struck down, but not destroyed." },
  { ref: "1 Corinthians 15:58", text: "Be steadfast and immovable, always abounding in the work of the Lord, for your labor is not in vain." },
  { ref: "Hebrews 10:36", text: "You need endurance to do the will of God and receive what He has promised." },
  { ref: "2 Thessalonians 3:13", text: "Do not grow weary in doing what is right." },
  { ref: "Romans 12:12", text: "Rejoice in hope, be patient in affliction, persevere in prayer." },
  { ref: "Luke 9:62", text: "No one who sets a hand to the plow and looks back is fit for the kingdom of God." },
  { ref: "Proverbs 24:16", text: "Though the just may fall seven times, they rise again." },
  { ref: "Matthew 24:13", text: "The one who perseveres to the end will be saved." },
  { ref: "1 Corinthians 16:13", text: "Be watchful, stand firm in the faith, be courageous, be strong." },
  { ref: "James 1:2-4", text: "Consider it pure joy when you face trials, for the testing of your faith produces perseverance." },
  { ref: "Sirach 2:4-5", text: "Accept whatever befalls you; in time of humiliation be patient, for in fire gold is tested." },
  { ref: "2 Corinthians 4:16", text: "We do not lose heart; though our outer self decays, our inner self is renewed day by day." },
  { ref: "Habakkuk 2:3", text: "If the vision delays, wait for it; it will surely come and will not be late." },
  { ref: "Philippians 3:14", text: "I press on toward the goal for the prize of God's heavenly call in Christ Jesus." },
  { ref: "Proverbs 21:31", text: "The horse is made ready for the day of battle, but victory belongs to the Lord." },
  { ref: "Joshua 1:9", text: "Be strong and courageous; do not be afraid, for the Lord your God is with you wherever you go." },
  { ref: "Isaiah 41:10", text: "Do not fear, for I am with you; I will strengthen you and uphold you with my right hand." },
  { ref: "Psalm 46:1", text: "God is our refuge and strength, an ever-present help in distress." },
  { ref: "Philippians 4:6-7", text: "Have no anxiety, but in everything, by prayer, make your requests known to God." },
  { ref: "Matthew 6:33", text: "Seek first the kingdom of God, and all these things will be given to you besides." },
  { ref: "Proverbs 3:5-6", text: "Trust in the Lord with all your heart; in all your ways acknowledge Him, and He will make your paths straight." },
  { ref: "Psalm 37:5", text: "Commit your way to the Lord; trust in Him, and He will act." },
  { ref: "Jeremiah 29:11", text: "I know the plans I have for you: plans for your welfare, to give you a future and a hope." },
  { ref: "John 15:5", text: "I am the vine, you are the branches; whoever remains in me bears much fruit." },
  { ref: "Psalm 23:1", text: "The Lord is my shepherd; there is nothing I shall want." },
  { ref: "Matthew 11:28", text: "Come to me, all you who labor and are burdened, and I will give you rest." },
  { ref: "Psalm 27:1", text: "The Lord is my light and my salvation; whom should I fear?" },
  { ref: "Nehemiah 8:10", text: "The joy of the Lord is your strength." },
  { ref: "2 Corinthians 12:9", text: "My grace is sufficient for you, for power is made perfect in weakness." },
  { ref: "Psalm 121:1-2", text: "My help comes from the Lord, the maker of heaven and earth." },
  { ref: "Wisdom 3:1", text: "The souls of the just are in the hand of God, and no torment shall touch them." },
  { ref: "Deuteronomy 31:6", text: "Be strong and steadfast; the Lord your God goes with you and will never forsake you." },
  { ref: "Isaiah 40:29", text: "He gives strength to the weary and abundant might to the powerless." },
  { ref: "Psalm 18:32", text: "It is God who arms me with strength and makes my way perfect." },
  { ref: "Ecclesiastes 4:9-10", text: "Two are better than one; if one falls, the other can help the fallen one up." },
  { ref: "Ecclesiastes 4:12", text: "A three-ply cord is not easily broken." },
  { ref: "1 Corinthians 12:12", text: "The body is one and has many parts, but all the parts form one body." },
  { ref: "1 Corinthians 12:14", text: "A body is not a single part, but many." },
  { ref: "Romans 12:4-5", text: "We, though many, are one body in Christ, and individually parts of one another." },
  { ref: "Philippians 2:2", text: "Be of the same mind, with the same love, united in heart, thinking one thing." },
  { ref: "Proverbs 27:17", text: "As iron sharpens iron, so one person sharpens another." },
  { ref: "Psalm 133:1", text: "How good and pleasant it is when brothers dwell together as one." },
  { ref: "Amos 3:3", text: "Can two walk together unless they have agreed to do so?" },
  { ref: "Sirach 6:14", text: "A faithful friend is a sturdy shelter; whoever finds one finds a treasure." },
  { ref: "Sirach 6:16", text: "A faithful friend is life-saving medicine, found only by those who fear the Lord." },
  { ref: "Galatians 6:2", text: "Bear one another's burdens, and so fulfill the law of Christ." },
  { ref: "Hebrews 10:24", text: "Let us be concerned for one another, to stir up love and good works." },
  { ref: "1 Thessalonians 5:11", text: "Encourage one another and build one another up." },
  { ref: "Exodus 17:12", text: "Aaron and Hur held up Moses' hands, one on each side, so they stayed steady until sunset." },
  { ref: "Romans 8:31", text: "If God is for us, who can be against us?" },
  { ref: "Isaiah 54:17", text: "No weapon fashioned against you will prevail." },
  { ref: "Psalm 118:6", text: "The Lord is with me; I am not afraid. What can anyone do to me?" },
  { ref: "Galatians 1:10", text: "If I were still trying to please people, I would not be a servant of Christ." },
  { ref: "Proverbs 29:25", text: "Fear of others becomes a snare, but whoever trusts in the Lord is safe." },
  { ref: "Matthew 5:11", text: "Blessed are you when they insult and persecute you and utter every kind of evil against you falsely." },
  { ref: "2 Timothy 1:7", text: "God did not give us a spirit of cowardice, but of power, love, and self-control." },
  { ref: "Nehemiah 6:3", text: "I am doing a great work and cannot come down; why should the work stop while I leave it?" },
  { ref: "Nehemiah 4:14", text: "Do not be afraid of them; remember the Lord, who is great and awesome." },
  { ref: "Acts 5:29", text: "We must obey God rather than men." },
  { ref: "1 Peter 3:14", text: "Do not be afraid or disturbed by what they fear." },
  { ref: "Isaiah 51:7", text: "Do not fear the reproach of others; do not be dismayed at their insults." },
  { ref: "Psalm 27:3", text: "Though an army encamp against me, my heart will not fear." },
  { ref: "1 Maccabees 3:19", text: "Victory in battle does not depend on the size of the army; strength comes from Heaven." },
  { ref: "1 Corinthians 4:3", text: "It is a very small thing that I should be judged by you or by any human court." },
  { ref: "Matthew 5:16", text: "Let your light shine before others, that they may see your good deeds and glorify your Father." },
  { ref: "Mark 10:43-44", text: "Whoever wishes to be great among you must be your servant." },
  { ref: "Matthew 20:28", text: "The Son of Man came not to be served but to serve." },
  { ref: "Galatians 5:13", text: "Through love, serve one another." },
  { ref: "1 Peter 4:10", text: "As each has received a gift, use it to serve one another as good stewards of God's grace." },
  { ref: "Micah 6:8", text: "Do justice, love goodness, and walk humbly with your God." },
  { ref: "Matthew 5:14", text: "You are the light of the world. A city set on a mountain cannot be hidden." },
  { ref: "John 13:14-15", text: "If I, your Lord, have washed your feet, you also ought to wash one another's feet." },
  { ref: "Colossians 3:23", text: "Whatever you do, do it from the heart, as for the Lord and not for others." },
  { ref: "Romans 12:11", text: "Do not be slothful in zeal; be fervent in spirit; serve the Lord." },
  { ref: "Jeremiah 29:7", text: "Seek the welfare of the city, for in its welfare you will find your own." },
  { ref: "Philippians 2:3-4", text: "Look out not only for your own interests, but also for the interests of others." },
  { ref: "Acts 20:35", text: "It is more blessed to give than to receive." },
  { ref: "Proverbs 19:17", text: "Whoever cares for the poor lends to the Lord, who will repay the kindness." },
  { ref: "Proverbs 22:9", text: "The generous are blessed, for they share their bread with the poor." },
  { ref: "2 Corinthians 9:7", text: "God loves a cheerful giver." },
  { ref: "Luke 6:38", text: "Give, and it will be given to you—a good measure, packed together, shaken down, and overflowing." },
  { ref: "Proverbs 11:25", text: "A generous person will prosper; whoever refreshes others will be refreshed." },
  { ref: "Proverbs 28:27", text: "Whoever gives to the poor will lack nothing." },
  { ref: "Matthew 25:40", text: "Whatever you did for one of these least brothers of mine, you did for me." },
  { ref: "Deuteronomy 15:11", text: "Open your hand freely to your poor and needy neighbor in your land." },
  { ref: "Tobit 4:7", text: "Give alms from your possessions, and do not turn your face away from any of the poor." },
  { ref: "Tobit 12:8-9", text: "Prayer with fasting and almsgiving is good; almsgiving saves from death and purges every sin." },
  { ref: "Sirach 4:1", text: "My child, do not cheat the poor of their living, or keep needy eyes waiting." },
  { ref: "Sirach 29:12", text: "Store up almsgiving in your treasury, and it will rescue you from every disaster." },
  { ref: "Luke 12:48", text: "Much will be required of the person entrusted with much." },
  { ref: "2 Corinthians 9:6", text: "Whoever sows sparingly will reap sparingly, and whoever sows bountifully will reap bountifully." },
  { ref: "Hebrews 13:16", text: "Do not neglect to do good and to share what you have, for such sacrifices please God." },
];
