import type {
  EquityPool,
  EquityProposal,
  EquityRoleBand,
  EquityStakeholder,
} from "@/lib/equity/types";

export const EQUITY_AS_OF_DATE = "2026-06-05";

export const EQUITY_POOL: EquityPool = {
  fullyDilutedShares: 10_000_000,
  founderAllocatedBps: 7_200,
  employeePoolBps: 1_200,
  advisorPoolBps: 300,
  strategicReserveBps: 1_300,
};

export const EQUITY_ROLE_BANDS: EquityRoleBand[] = [
  {
    id: "cofounder-operator",
    label: "Cofounder-level operator",
    benchmarkLowBps: 350,
    benchmarkHighBps: 900,
    defaultBps: 600,
    defaultVestingMonths: 48,
    defaultCliffMonths: 12,
    recommendedDeliverables: [
      "Own executive operating cadence",
      "Deliver first repeatable revenue motion",
      "Recruit and manage first functional team",
    ],
  },
  {
    id: "functional-lead",
    label: "Functional lead",
    benchmarkLowBps: 75,
    benchmarkHighBps: 250,
    defaultBps: 150,
    defaultVestingMonths: 48,
    defaultCliffMonths: 12,
    recommendedDeliverables: [
      "Build function operating plan",
      "Own quarterly KPI target",
      "Document process and hiring needs",
    ],
  },
  {
    id: "strategic-partner",
    label: "Strategic partner",
    benchmarkLowBps: 25,
    benchmarkHighBps: 125,
    defaultBps: 60,
    defaultVestingMonths: 36,
    defaultCliffMonths: 6,
    recommendedDeliverables: [
      "Introduce qualified enterprise opportunities",
      "Support commercial diligence",
      "Convert at least one signed channel opportunity",
    ],
  },
  {
    id: "advisor",
    label: "Advisor",
    benchmarkLowBps: 10,
    benchmarkHighBps: 50,
    defaultBps: 25,
    defaultVestingMonths: 24,
    defaultCliffMonths: 3,
    recommendedDeliverables: [
      "Monthly advisory session",
      "Targeted introductions with CRM notes",
      "Review strategy artifact before board cycle",
    ],
  },
];

export const EQUITY_STAKEHOLDERS: EquityStakeholder[] = [
  {
    id: "eq-ana",
    name: "Ana M.",
    role: "Founding Product Lead",
    team: "Product",
    grantType: "stock_option",
    status: "active",
    ownershipBps: 180,
    vesting: {
      startDate: "2025-07-01",
      cliffMonths: 12,
      durationMonths: 48,
      cadence: "monthly",
    },
    accessLevel: "recipient",
    lastReviewDate: "2026-04-15",
    nextReviewDate: "2026-07-15",
    notes: "Grant tied to shipping CRM operating modules and design quality.",
    deliverables: [
      {
        id: "ana-d1",
        title: "Equity-ready project workspace shipped",
        owner: "Ana M.",
        status: "complete",
        dueDate: "2026-03-31",
        weight: 35,
        verification: "Production release notes and QA evidence",
        roleImpact: "core",
      },
      {
        id: "ana-d2",
        title: "CRM adoption above 75% weekly active users",
        owner: "Ana M.",
        status: "in_progress",
        dueDate: "2026-07-31",
        weight: 40,
        verification: "Dashboard analytics and team survey",
        roleImpact: "core",
      },
      {
        id: "ana-d3",
        title: "Design system review cadence installed",
        owner: "Ana M.",
        status: "complete",
        dueDate: "2026-05-15",
        weight: 25,
        verification: "UX review checklist attached to sprint close",
        roleImpact: "supporting",
      },
    ],
  },
  {
    id: "eq-marco",
    name: "Marco R.",
    role: "Revenue Advisor",
    team: "Growth",
    grantType: "stock_option",
    status: "active",
    ownershipBps: 35,
    vesting: {
      startDate: "2026-01-01",
      cliffMonths: 3,
      durationMonths: 24,
      cadence: "quarterly",
    },
    accessLevel: "reviewer",
    lastReviewDate: "2026-03-20",
    nextReviewDate: "2026-06-20",
    notes: "Advisor grant tied to verified enterprise introductions.",
    deliverables: [
      {
        id: "marco-d1",
        title: "Five qualified partner intros logged",
        owner: "Marco R.",
        status: "complete",
        dueDate: "2026-04-30",
        weight: 45,
        verification: "CRM contacts with meeting notes",
        roleImpact: "core",
      },
      {
        id: "marco-d2",
        title: "Two partner pilots reach proposal stage",
        owner: "Marco R.",
        status: "at_risk",
        dueDate: "2026-06-30",
        weight: 55,
        verification: "Pipeline stage and signed next-step email",
        roleImpact: "core",
      },
    ],
  },
  {
    id: "eq-lina",
    name: "Lina S.",
    role: "Ops Systems Lead",
    team: "Operations",
    grantType: "stock_option",
    status: "vesting_paused",
    ownershipBps: 90,
    vesting: {
      startDate: "2025-10-01",
      cliffMonths: 12,
      durationMonths: 48,
      cadence: "monthly",
    },
    accessLevel: "recipient",
    lastReviewDate: "2026-02-01",
    nextReviewDate: "2026-05-01",
    notes: "Pause pending acceptance criteria for finance operations automation.",
    deliverables: [
      {
        id: "lina-d1",
        title: "Treasury reconciliation process operating weekly",
        owner: "Lina S.",
        status: "blocked",
        dueDate: "2026-05-31",
        weight: 60,
        verification: "Weekly close checklist with owner sign-off",
        roleImpact: "core",
      },
      {
        id: "lina-d2",
        title: "Vendor controls and approval policy documented",
        owner: "Lina S.",
        status: "in_progress",
        dueDate: "2026-06-30",
        weight: 40,
        verification: "Policy doc plus first approval audit",
        roleImpact: "supporting",
      },
    ],
  },
];

export const EQUITY_PROPOSALS: EquityProposal[] = [
  {
    id: "prop-strategic-gm",
    candidateName: "Strategic GM Candidate",
    roleBandId: "functional-lead",
    roleTitle: "General Manager, Strategic Accounts",
    proposedBps: 140,
    grantType: "stock_option",
    stage: "needs_review",
    rationale:
      "Would own enterprise account operating cadence, partner access, and first repeatable strategic-account playbook.",
    vesting: {
      startDate: "2026-07-01",
      cliffMonths: 12,
      durationMonths: 48,
      cadence: "monthly",
    },
    deliverables: [
      {
        id: "gm-d1",
        title: "Close 3 strategic account design partners",
        owner: "Strategic GM Candidate",
        status: "not_started",
        dueDate: "2026-10-31",
        weight: 40,
        verification: "Signed LOI or paid pilot in CRM",
        roleImpact: "core",
      },
      {
        id: "gm-d2",
        title: "Build operating dashboard for account health",
        owner: "Strategic GM Candidate",
        status: "not_started",
        dueDate: "2026-09-30",
        weight: 25,
        verification: "Live CRM dashboard reviewed by founders",
        roleImpact: "core",
      },
      {
        id: "gm-d3",
        title: "Document handoff process for delivery team",
        owner: "Strategic GM Candidate",
        status: "not_started",
        dueDate: "2026-11-15",
        weight: 35,
        verification: "Approved SOP and first handoff retro",
        roleImpact: "supporting",
      },
    ],
  },
];
